spring:
  application:
    name: gateway-service
    
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
zuul:
  routes:
    department-service:
      path: /department/**
    employee-service:
      path: /employee/**
    organization-service:
      path: /organization/**